import { test, expect, describe } from "bun:test";
import { DocxNodeVisitor } from "../src/compiler/visitors/docx-visitor";
import { createContext } from "../src/compiler/context";
import type { ModifierNode, ParagraphNode } from "../src/parser/ast";

/**
 * Helper to extract the alignment value from a docx Table generated by @box.
 * Navigates: Table -> TableRow -> TableCell -> Paragraph -> ParagraphProperties -> Alignment
 */
function extractAlignmentFromBoxTable(table: any): string {
  // Find TableRow in table.root (skip TableProperties, TableGrid)
  const tableRow = table.root.find((item: any) => item.constructor.name === "TableRow");
  if (!tableRow) throw new Error("TableRow not found");

  // Find TableCell in row.root (skip TableRowProperties)
  const tableCell = tableRow.root.find((item: any) => item.constructor.name === "TableCell");
  if (!tableCell) throw new Error("TableCell not found");

  // Find Paragraph in cell.root (skip TableCellProperties)
  const paragraph = tableCell.root.find((item: any) => item.constructor.name === "Paragraph");
  if (!paragraph) throw new Error("Paragraph not found");

  // Find ParagraphProperties in paragraph.root
  const paragraphProps = paragraph.root.find((item: any) => item.constructor.name === "ParagraphProperties");
  if (!paragraphProps) throw new Error("ParagraphProperties not found");

  // Find Alignment in props.root
  const alignment = paragraphProps.root.find((item: any) => item.constructor.name === "Alignment");
  if (!alignment) throw new Error("Alignment not found");

  // Extract value from alignment.root[0].root.val
  const alignmentAttrs = alignment.root[0];
  if (!alignmentAttrs || !alignmentAttrs.root) throw new Error("AlignmentAttributes not found");

  return alignmentAttrs.root.val;
}

describe("Alignment Inheritance", () => {
  test("text inside @box inherits alignment from outer @center", () => {
    // Create the AST: @center wrapping @box wrapping a paragraph
    const ast: ModifierNode = {
      type: "modifier",
      modifier: "center",
      line: 1,
      column: 0,
      content: [{
        type: "modifier",
        modifier: "box",
        line: 2,
        column: 2,
        content: [{
          type: "paragraph",
          line: 3,
          column: 4,
          content: [{ type: "text", value: "Centered Text" }]
        } as ParagraphNode]
      } as ModifierNode]
    };

    // Compile using DocxNodeVisitor
    const ctx = createContext();
    const visitor = new DocxNodeVisitor(ctx);
    const result = visitor.visit(ast);

    // The result should be a single Table (from @box)
    expect(result).toHaveLength(1);
    const table = result[0];
    expect(table).toBeDefined();
    expect(table!.constructor.name).toBe("Table");

    // Extract and verify alignment
    const alignmentValue = extractAlignmentFromBoxTable(table);
    expect(alignmentValue).toBe("center");
  });

  test("@box without outer alignment defaults to left alignment", () => {
    // Create the AST: @box wrapping a paragraph (no @center)
    const ast: ModifierNode = {
      type: "modifier",
      modifier: "box",
      line: 1,
      column: 0,
      content: [{
        type: "paragraph",
        line: 2,
        column: 2,
        content: [{ type: "text", value: "Left-aligned Text" }]
      } as ParagraphNode]
    };

    // Compile using DocxNodeVisitor
    const ctx = createContext();
    const visitor = new DocxNodeVisitor(ctx);
    const result = visitor.visit(ast);

    // The result should be a single Table (from @box)
    expect(result).toHaveLength(1);
    const table = result[0];
    expect(table).toBeDefined();
    expect(table!.constructor.name).toBe("Table");

    // Extract and verify alignment
    const alignmentValue = extractAlignmentFromBoxTable(table);
    expect(alignmentValue).toBe("left");
  });

  test("@right alignment propagates through @box", () => {
    // Create the AST: @right wrapping @box wrapping a paragraph
    const ast: ModifierNode = {
      type: "modifier",
      modifier: "right",
      line: 1,
      column: 0,
      content: [{
        type: "modifier",
        modifier: "box",
        line: 2,
        column: 2,
        content: [{
          type: "paragraph",
          line: 3,
          column: 4,
          content: [{ type: "text", value: "Right-aligned Text" }]
        } as ParagraphNode]
      } as ModifierNode]
    };

    // Compile using DocxNodeVisitor
    const ctx = createContext();
    const visitor = new DocxNodeVisitor(ctx);
    const result = visitor.visit(ast);

    // The result should be a single Table (from @box)
    expect(result).toHaveLength(1);
    const table = result[0];
    expect(table).toBeDefined();
    expect(table!.constructor.name).toBe("Table");

    // Extract and verify alignment
    const alignmentValue = extractAlignmentFromBoxTable(table);
    expect(alignmentValue).toBe("right");
  });
});
