import { test, expect, describe } from "bun:test";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { Parser } from "../src/parser/parser";
import { compile } from "../src/compiler";
import { decompile } from "../src/decompiler";
import { format } from "../src/formatter";

// Strip @anchor directives for comparison since they may be generated by compiler for headings
function stripAnchors(ldoc: string): string {
  return ldoc
    .split("\n")
    .filter((line) => !line.trim().startsWith("@anchor "))
    .join("\n");
}

describe("Round Trip", () => {
  test("compile -> decompile preserves static LDOC structure", async () => {
    // 1. Read the fixture
    const fixturePath = resolve(import.meta.dir, "fixtures/round_trip.ldoc");
    const originalSource = await readFile(fixturePath, "utf-8");

    // 2. Parse and compile to DOCX
    const parser = new Parser();
    const ast = parser.parse(originalSource);
    const docxBuffer = await compile(ast);

    // 3. Decompile back to LDOC
    const result = await decompile(docxBuffer);
    const decompiled = result.source;

    // 4. Format both for comparison
    const formattedOriginal = format(originalSource, { useTabs: true });
    const formattedDecompiled = format(decompiled, { useTabs: true });
    
    // 5. Strip anchors for comparison (compiler may add bookmarks to headings)
    const originalNoAnchors = stripAnchors(formattedOriginal);
    const decompiledNoAnchors = stripAnchors(formattedDecompiled);

    // 6. Compare
    if (originalNoAnchors !== decompiledNoAnchors) {
      console.log("\n=== ORIGINAL (formatted) ===");
      console.log(formattedOriginal);
      console.log("\n=== DECOMPILED (formatted) ===");
      console.log(formattedDecompiled);
      console.log("\n=== DIFF ===");

      const originalLines = originalNoAnchors.split("\n");
      const decompiledLines = decompiledNoAnchors.split("\n");
      const maxLines = Math.max(originalLines.length, decompiledLines.length);

      for (let i = 0; i < maxLines; i++) {
        const origLine = originalLines[i] ?? "";
        const decompLine = decompiledLines[i] ?? "";
        if (origLine !== decompLine) {
          console.log(`Line ${i + 1}:`);
          console.log(`  - original:   "${origLine}"`);
          console.log(`  + decompiled: "${decompLine}"`);
        }
      }
    }

    expect(decompiledNoAnchors).toBe(originalNoAnchors);
  });
});
